# Generated by Django 4.0.5 on 2022-07-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
