# Generated by Django 4.0.5 on 2022-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='secret_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
