# Generated by Django 4.0.5 on 2022-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_secret_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
