# Generated by Django 4.0.5 on 2022-07-08 00:48

import complexes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('parking', models.IntegerField()),
                ('heating', models.CharField(choices=[('center', 'Center'), ('local', 'Local'), ('parti', 'Parti')], max_length=6)),
                ('approval_use', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex', to='complexes.category')),
            ],
            options={
                'verbose_name_plural': 'Complexes',
            },
        ),
        migrations.CreateModel(
            name='ComplexArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply_area', models.FloatField()),
                ('exclusive_private_area', models.FloatField()),
                ('room', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_area', to='complexes.complex')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('apartment', models.IntegerField()),
                ('facing', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('complex_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_sub', to='complexes.complexarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=complexes.models.complex_directory_path)),
                ('description', models.TextField()),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_image', to='complexes.complex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
