# Generated by Django 4.0.5 on 2022-06-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compleximage',
            old_name='desciption',
            new_name='description',
        ),
    ]
