# Generated by Django 4.0.5 on 2022-06-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0002_rename_desciption_compleximage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complexsub',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
