# Generated by Django 4.0.5 on 2022-07-04 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0003_rename_logitude_complexsub_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
