# Generated by Django 4.0.5 on 2022-07-08 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('jeonse', 'Jeonse'), ('monthly', 'Monthly')], max_length=7)),
                ('deposit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.IntegerField()),
                ('loan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('administrative_expense', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available_date', models.DateField()),
                ('description', models.TextField()),
                ('one_description', models.TextField()),
                ('is_sold', models.BooleanField()),
                ('complex_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='complexes.complexsub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=sales.models.sale_directory_path)),
                ('description', models.TextField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_image', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
