# Generated by Django 4.0.5 on 2022-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('jeonse', 'Jeonse'), ('monthly', 'Monthly')], max_length=7),
        ),
    ]
