# Generated by Django 4.0.5 on 2022-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_administrative_expense_alter_sale_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
